fail_fast: true

repos:
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: "v0.0.262"
    hooks:
      - id: ruff
        language_version: python3
        args: [--exit-zero, --show-fixes,  --extend-exclude, "explore/"]
  - repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
      - id: black
        language_version: python3
        args: ['--preview', --extend-exclude, "_schema/", --extend-exclude, "explore/"]